repos:
- repo: https://github.com/tekwizely/pre-commit-golang
  rev: v1.0.0-rc.4
  hooks:
    - id: go-fumpt
    - id: go-mod-tidy
    - id: go-lint
    - id: go-imports
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
